# Stage 1: Build
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration production

# Stage 2: Serve
FROM nginx:alpine
COPY --from=build /app/dist/calendary.ng/browser /usr/share/nginx/html
COPY nginx.production.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
