// <auto-generated />
using System;
using Calendary.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calendary.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831184128_AddPromptLibrary")]
    partial class AddPromptLibrary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Calendary.Domain.Entities.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ImageGenerationProvider")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            ImageGenerationProvider = 1
                        });
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.ImageStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImageStyles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555501"),
                            Name = "Фотореалізм",
                            SortOrder = 1,
                            Text = "photorealistic photography, cinematic lighting, rich detail"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555502"),
                            Name = "Графіка",
                            SortOrder = 2,
                            Text = "detailed pencil and ink illustration, hand-drawn graphic art, fine linework"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555503"),
                            Name = "Чорно-біле",
                            SortOrder = 3,
                            Text = "black and white photography, dramatic monochrome contrast, timeless mood"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555504"),
                            Name = "3D-мультфільм",
                            SortOrder = 4,
                            Text = "3D animated feature film style, expressive stylized character, vibrant colors, soft lighting"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555505"),
                            Name = "Аніме",
                            SortOrder = 5,
                            Text = "anime art style, clean linework, vivid cel shading, expressive eyes"
                        });
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RegenerationsRemaining")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("StatusUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.PersonalDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("PersonalDates");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Prompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PromptThemeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PromptThemeId");

                    b.ToTable("Prompts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            Name = "Вікінг",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333301"),
                            SortOrder = 1,
                            Text = "a fierce Viking warrior with authentic period clothing, armor, and props, in a rugged northern landscape"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444402"),
                            Name = "Фараон",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333301"),
                            SortOrder = 2,
                            Text = "an Egyptian pharaoh in ceremonial regalia with golden ornaments, amid ancient temple architecture"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444403"),
                            Name = "Самурай",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333301"),
                            SortOrder = 3,
                            Text = "a samurai in traditional lacquered armor with a katana, in a feudal Japanese setting"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444404"),
                            Name = "Лицар",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333301"),
                            SortOrder = 4,
                            Text = "a medieval knight in polished plate armor with heraldic details, near a stone castle"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444405"),
                            Name = "Козак",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333301"),
                            SortOrder = 5,
                            Text = "a Ukrainian Cossack with traditional attire, shaved head with an oseledets, and a saber, on the open steppe"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444406"),
                            Name = "Нуар-детектив",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333302"),
                            SortOrder = 1,
                            Text = "a film noir detective in a trench coat and fedora, moody city streets with dramatic shadows"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444407"),
                            Name = "Ковбой вестерну",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333302"),
                            SortOrder = 2,
                            Text = "a spaghetti western gunslinger with a poncho and revolver, in a dusty frontier town"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444408"),
                            Name = "Шпигун",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333302"),
                            SortOrder = 3,
                            Text = "an elegant secret agent in a tailored suit with spy gadgets, in a glamorous casino or rooftop scene"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444409"),
                            Name = "Зірка мюзиклу",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333302"),
                            SortOrder = 4,
                            Text = "a golden-age musical performer in a dazzling stage costume, under theatrical spotlights"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444418"),
                            Name = "Супергерой",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333302"),
                            SortOrder = 5,
                            Text = "a superhero in a sleek costume with a flowing cape, dramatic pose over a night city skyline"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444410"),
                            Name = "Альпініст",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333303"),
                            SortOrder = 1,
                            Text = "a mountaineer with climbing gear and ropes, high on a dramatic snowy peak"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444411"),
                            Name = "Пілот",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333303"),
                            SortOrder = 2,
                            Text = "a bush pilot with a leather jacket and aviator goggles, beside a vintage propeller plane"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444412"),
                            Name = "Дайвер",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333303"),
                            SortOrder = 3,
                            Text = "a scuba diver with full diving gear, exploring a vivid coral reef underwater"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444413"),
                            Name = "Полярник",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333303"),
                            SortOrder = 4,
                            Text = "a polar explorer in an expedition parka with sled dogs, amid arctic ice fields"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444419"),
                            Name = "Дослідник джунглів",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333303"),
                            SortOrder = 5,
                            Text = "a jungle explorer with a khaki outfit and a machete, deep in lush tropical rainforest ruins"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444414"),
                            Name = "Шеф-кухар",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333304"),
                            SortOrder = 1,
                            Text = "a head chef in a pristine white uniform plating a dish, in a busy professional kitchen"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444415"),
                            Name = "Лікар",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333304"),
                            SortOrder = 2,
                            Text = "a doctor in a white coat with a stethoscope, in a bright modern hospital"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444416"),
                            Name = "Диригент",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333304"),
                            SortOrder = 3,
                            Text = "an orchestra conductor in a tailcoat mid-performance, baton raised before a grand orchestra"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444417"),
                            Name = "Пожежник",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333304"),
                            SortOrder = 4,
                            Text = "a firefighter in full turnout gear with a helmet, heroic pose near a fire engine"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444420"),
                            Name = "Астронавт",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333304"),
                            SortOrder = 5,
                            Text = "an astronaut in a detailed spacesuit with a reflective visor, beside a spacecraft under a starry sky"
                        });
                });

            modelBuilder.Entity("Calendary.Domain.Entities.PromptTheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PromptThemes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            Description = "вікінг, фараон, самурай, лицар, козак…",
                            Name = "Історія",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            Description = "нуар, вестерн, шпигун, мюзикл…",
                            Name = "Кіно",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            Description = "альпініст, пілот, дайвер, полярник…",
                            Name = "Пригоди",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333304"),
                            Description = "шеф, лікар, диригент, пожежник…",
                            Name = "Професії",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Sheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("GeneratingStartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ImageStyleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PromptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReadyAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VariantCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageStyleId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PromptId");

                    b.ToTable("Sheets");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailConfirmationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailConfirmationCodeExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Delivery", b =>
                {
                    b.HasOne("Calendary.Domain.Entities.Order", "Order")
                        .WithOne("Delivery")
                        .HasForeignKey("Calendary.Domain.Entities.Delivery", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Order", b =>
                {
                    b.HasOne("Calendary.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Calendary.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Calendary.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.PersonalDate", b =>
                {
                    b.HasOne("Calendary.Domain.Entities.Order", "Order")
                        .WithMany("PersonalDates")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Prompt", b =>
                {
                    b.HasOne("Calendary.Domain.Entities.PromptTheme", "PromptTheme")
                        .WithMany("Prompts")
                        .HasForeignKey("PromptThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromptTheme");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Sheet", b =>
                {
                    b.HasOne("Calendary.Domain.Entities.ImageStyle", "ImageStyle")
                        .WithMany()
                        .HasForeignKey("ImageStyleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Calendary.Domain.Entities.Order", "Order")
                        .WithMany("Sheets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Calendary.Domain.Entities.Prompt", "Prompt")
                        .WithMany()
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ImageStyle");

                    b.Navigation("Order");

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("Calendary.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Order", b =>
                {
                    b.Navigation("Delivery");

                    b.Navigation("Payment");

                    b.Navigation("PersonalDates");

                    b.Navigation("Sheets");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.PromptTheme", b =>
                {
                    b.Navigation("Prompts");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
