// <auto-generated />
using System;
using Calendary.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calendary.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921094658_AddRealIntegrationsOnStagingSetting")]
    partial class AddRealIntegrationsOnStagingSetting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Calendary.Domain.Entities.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ImageGenerationProvider")
                        .HasColumnType("int");

                    b.Property<bool>("RealIntegrationsOnStaging")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            BasePrice = 1600m,
                            ImageGenerationProvider = 1,
                            RealIntegrationsOnStaging = false
                        });
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CityRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WarehouseRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770001"),
                            Country = 0,
                            Day = 1,
                            Month = 1,
                            Name = "Новий рік",
                            ShortName = "Новий рік",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770004"),
                            Country = 0,
                            Day = 1,
                            Month = 5,
                            Name = "День праці",
                            ShortName = "День праці",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770005"),
                            Country = 0,
                            Day = 9,
                            Month = 5,
                            Name = "День перемоги над нацизмом у Другій світовій війні",
                            ShortName = "День перемоги",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770006"),
                            Country = 0,
                            Day = 28,
                            Month = 6,
                            Name = "День Конституції України",
                            ShortName = "День Конституції",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770007"),
                            Country = 0,
                            Day = 24,
                            Month = 8,
                            Name = "День незалежності України",
                            ShortName = "День незалежності",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770008"),
                            Country = 0,
                            Day = 1,
                            Month = 10,
                            Name = "День захисників і захисниць України",
                            ShortName = "День захисників",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770009"),
                            Country = 0,
                            Day = 25,
                            Month = 12,
                            Name = "Різдво Христове (григоріанський календар)",
                            ShortName = "Різдво",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770101"),
                            Country = 1,
                            Day = 1,
                            Month = 1,
                            Name = "New Year's Day",
                            ShortName = "New Year",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770102"),
                            Country = 1,
                            Day = 18,
                            Month = 1,
                            Name = "Martin Luther King Jr. Day",
                            ShortName = "MLK Day",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770103"),
                            Country = 1,
                            Day = 15,
                            Month = 2,
                            Name = "Washington's Birthday",
                            ShortName = "Presidents Day",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770104"),
                            Country = 1,
                            Day = 31,
                            Month = 5,
                            Name = "Memorial Day",
                            ShortName = "Memorial Day",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770105"),
                            Country = 1,
                            Day = 19,
                            Month = 6,
                            Name = "Juneteenth",
                            ShortName = "Juneteenth",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770106"),
                            Country = 1,
                            Day = 4,
                            Month = 7,
                            Name = "Independence Day",
                            ShortName = "July 4th",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770107"),
                            Country = 1,
                            Day = 6,
                            Month = 9,
                            Name = "Labor Day",
                            ShortName = "Labor Day",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770108"),
                            Country = 1,
                            Day = 11,
                            Month = 10,
                            Name = "Columbus Day",
                            ShortName = "Columbus Day",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770109"),
                            Country = 1,
                            Day = 11,
                            Month = 11,
                            Name = "Veterans Day",
                            ShortName = "Veterans Day",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770110"),
                            Country = 1,
                            Day = 25,
                            Month = 11,
                            Name = "Thanksgiving Day",
                            ShortName = "Thanksgiving",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770111"),
                            Country = 1,
                            Day = 25,
                            Month = 12,
                            Name = "Christmas Day",
                            ShortName = "Christmas",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770201"),
                            Country = 2,
                            Day = 1,
                            Month = 1,
                            Name = "Nowy Rok",
                            ShortName = "Nowy Rok",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770202"),
                            Country = 2,
                            Day = 6,
                            Month = 1,
                            Name = "Święto Trzech Króli",
                            ShortName = "Trzech Króli",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770203"),
                            Country = 2,
                            Day = 28,
                            Month = 3,
                            Name = "Wielkanoc",
                            ShortName = "Wielkanoc",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770204"),
                            Country = 2,
                            Day = 29,
                            Month = 3,
                            Name = "Poniedziałek Wielkanocny",
                            ShortName = "Lany Poniedziałek",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770205"),
                            Country = 2,
                            Day = 1,
                            Month = 5,
                            Name = "Święto Pracy",
                            ShortName = "Święto Pracy",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770206"),
                            Country = 2,
                            Day = 3,
                            Month = 5,
                            Name = "Święto Konstytucji 3 Maja",
                            ShortName = "3 Maja",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770207"),
                            Country = 2,
                            Day = 16,
                            Month = 5,
                            Name = "Zielone Świątki",
                            ShortName = "Zielone Świątki",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770208"),
                            Country = 2,
                            Day = 27,
                            Month = 5,
                            Name = "Boże Ciało",
                            ShortName = "Boże Ciało",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770209"),
                            Country = 2,
                            Day = 15,
                            Month = 8,
                            Name = "Wniebowzięcie Najświętszej Maryi Panny",
                            ShortName = "Wniebowzięcie NMP",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770210"),
                            Country = 2,
                            Day = 1,
                            Month = 11,
                            Name = "Wszystkich Świętych",
                            ShortName = "Wsz. Świętych",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770211"),
                            Country = 2,
                            Day = 11,
                            Month = 11,
                            Name = "Święto Niepodległości",
                            ShortName = "Niepodległości",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770212"),
                            Country = 2,
                            Day = 25,
                            Month = 12,
                            Name = "Boże Narodzenie (pierwszy dzień)",
                            ShortName = "Boże Narodz. I",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770213"),
                            Country = 2,
                            Day = 26,
                            Month = 12,
                            Name = "Boże Narodzenie (drugi dzień)",
                            ShortName = "Boże Narodz. II",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770301"),
                            Country = 3,
                            Day = 1,
                            Month = 1,
                            Name = "Neujahr",
                            ShortName = "Neujahr",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770302"),
                            Country = 3,
                            Day = 26,
                            Month = 3,
                            Name = "Karfreitag",
                            ShortName = "Karfreitag",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770303"),
                            Country = 3,
                            Day = 29,
                            Month = 3,
                            Name = "Ostermontag",
                            ShortName = "Ostermontag",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770304"),
                            Country = 3,
                            Day = 1,
                            Month = 5,
                            Name = "Tag der Arbeit",
                            ShortName = "Tag der Arbeit",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770305"),
                            Country = 3,
                            Day = 6,
                            Month = 5,
                            Name = "Christi Himmelfahrt",
                            ShortName = "Himmelfahrt",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770306"),
                            Country = 3,
                            Day = 17,
                            Month = 5,
                            Name = "Pfingstmontag",
                            ShortName = "Pfingstmontag",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770307"),
                            Country = 3,
                            Day = 3,
                            Month = 10,
                            Name = "Tag der Deutschen Einheit",
                            ShortName = "Dt. Einheit",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770308"),
                            Country = 3,
                            Day = 25,
                            Month = 12,
                            Name = "1. Weihnachtsfeiertag",
                            ShortName = "Weihnachten I",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770309"),
                            Country = 3,
                            Day = 26,
                            Month = 12,
                            Name = "2. Weihnachtsfeiertag",
                            ShortName = "Weihnachten II",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770401"),
                            Country = 4,
                            Day = 1,
                            Month = 1,
                            Name = "Den obnovy samostatného českého státu",
                            ShortName = "Obnovy státu",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770402"),
                            Country = 4,
                            Day = 26,
                            Month = 3,
                            Name = "Velký pátek",
                            ShortName = "Velký pátek",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770403"),
                            Country = 4,
                            Day = 29,
                            Month = 3,
                            Name = "Velikonoční pondělí",
                            ShortName = "Velikonoce",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770404"),
                            Country = 4,
                            Day = 1,
                            Month = 5,
                            Name = "Svátek práce",
                            ShortName = "Svátek práce",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770405"),
                            Country = 4,
                            Day = 8,
                            Month = 5,
                            Name = "Den vítězství",
                            ShortName = "Den vítězství",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770406"),
                            Country = 4,
                            Day = 5,
                            Month = 7,
                            Name = "Den slovanských věrozvěstů Cyrila a Metoděje",
                            ShortName = "Cyril a Metoděj",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770407"),
                            Country = 4,
                            Day = 6,
                            Month = 7,
                            Name = "Den upálení mistra Jana Husa",
                            ShortName = "Jan Hus",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770408"),
                            Country = 4,
                            Day = 28,
                            Month = 9,
                            Name = "Den české státnosti",
                            ShortName = "Česká státnost",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770409"),
                            Country = 4,
                            Day = 28,
                            Month = 10,
                            Name = "Den vzniku samostatného československého státu",
                            ShortName = "Vznik ČSR",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770410"),
                            Country = 4,
                            Day = 17,
                            Month = 11,
                            Name = "Den boje za svobodu a demokracii",
                            ShortName = "Boj za svobodu",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770411"),
                            Country = 4,
                            Day = 24,
                            Month = 12,
                            Name = "Štědrý den",
                            ShortName = "Štědrý den",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770412"),
                            Country = 4,
                            Day = 25,
                            Month = 12,
                            Name = "1. svátek vánoční",
                            ShortName = "Vánoce I",
                            Year = 2027
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777770413"),
                            Country = 4,
                            Day = 26,
                            Month = 12,
                            Name = "2. svátek vánoční",
                            ShortName = "Vánoce II",
                            Year = 2027
                        });
                });

            modelBuilder.Entity("Calendary.Domain.Entities.ImageStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImageStyles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555501"),
                            Description = "Наче справжня фотографія з кінематографічним світлом",
                            Name = "Фотореалізм",
                            SortOrder = 1,
                            Text = "photorealistic photography, cinematic lighting, rich detail"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555502"),
                            Description = "Витончений малюнок олівцем і тушшю від руки",
                            Name = "Графіка",
                            SortOrder = 2,
                            Text = "detailed pencil and ink illustration, hand-drawn graphic art, fine linework"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555503"),
                            Description = "Драматичний монохром із позачасовим настроєм",
                            Name = "Чорно-біле",
                            SortOrder = 3,
                            Text = "black and white photography, dramatic monochrome contrast, timeless mood"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555504"),
                            Description = "Яскравий персонаж у стилі анімаційного фільму",
                            Name = "3D-мультфільм",
                            SortOrder = 4,
                            Text = "3D animated feature film style, expressive stylized character, vibrant colors, soft lighting"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555505"),
                            Description = "Виразна японська анімація з чистими лініями",
                            Name = "Аніме",
                            SortOrder = 5,
                            Text = "anime art style, clean linework, vivid cel shading, expressive eyes"
                        });
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HolidayCountries")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("N'Ukraine'");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PrintQuantity")
                        .HasColumnType("int");

                    b.Property<string>("PromoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegenerationsRemaining")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("StatusUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WeekStart")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.OrderPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ThumbUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderPhotos");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusHistories");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProviderInvoiceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.PersonalDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("PersonalDates");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.PromoCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxRedemptions")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RedemptionsUsed")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidToUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Prompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PromptThemeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PromptThemeId");

                    b.ToTable("Prompts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            Description = "Суворий воїн півночі серед скель і фʼордів",
                            Name = "Вікінг",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333301"),
                            SortOrder = 1,
                            Text = "a fierce Viking warrior with authentic period clothing, armor, and props, in a rugged northern landscape"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444402"),
                            Description = "Володар Єгипту в золоті серед стародавніх храмів",
                            Name = "Фараон",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333301"),
                            SortOrder = 2,
                            Text = "an Egyptian pharaoh in ceremonial regalia with golden ornaments, amid ancient temple architecture"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444403"),
                            Description = "Воїн у лакованих обладунках з катаною в Японії",
                            Name = "Самурай",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333301"),
                            SortOrder = 3,
                            Text = "a samurai in traditional lacquered armor with a katana, in a feudal Japanese setting"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444404"),
                            Description = "Середньовічний лицар у латах біля камʼяного замку",
                            Name = "Лицар",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333301"),
                            SortOrder = 4,
                            Text = "a medieval knight in polished plate armor with heraldic details, near a stone castle"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444405"),
                            Description = "Козак з оселедцем і шаблею у відкритому степу",
                            Name = "Козак",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333301"),
                            SortOrder = 5,
                            Text = "a Ukrainian Cossack with traditional attire, shaved head with an oseledets, and a saber, on the open steppe"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444406"),
                            Description = "Детектив у плащі на темних вулицях міста",
                            Name = "Нуар-детектив",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333302"),
                            SortOrder = 1,
                            Text = "a film noir detective in a trench coat and fedora, moody city streets with dramatic shadows"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444407"),
                            Description = "Стрілець у пончо в запиленому містечку фронтиру",
                            Name = "Ковбой вестерну",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333302"),
                            SortOrder = 2,
                            Text = "a spaghetti western gunslinger with a poncho and revolver, in a dusty frontier town"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444408"),
                            Description = "Елегантний агент у костюмі в розкішному казино",
                            Name = "Шпигун",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333302"),
                            SortOrder = 3,
                            Text = "an elegant secret agent in a tailored suit with spy gadgets, in a glamorous casino or rooftop scene"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444409"),
                            Description = "Артист у блискучому костюмі під світлом прожекторів",
                            Name = "Зірка мюзиклу",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333302"),
                            SortOrder = 4,
                            Text = "a golden-age musical performer in a dazzling stage costume, under theatrical spotlights"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444418"),
                            Description = "Герой у плащі над вогнями нічного міста",
                            Name = "Супергерой",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333302"),
                            SortOrder = 5,
                            Text = "a superhero in a sleek costume with a flowing cape, dramatic pose over a night city skyline"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444410"),
                            Description = "Підкорювач вершин серед снігу та скель",
                            Name = "Альпініст",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333303"),
                            SortOrder = 1,
                            Text = "a mountaineer with climbing gear and ropes, high on a dramatic snowy peak"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444411"),
                            Description = "Авіатор у шкіряній куртці біля вінтажного літака",
                            Name = "Пілот",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333303"),
                            SortOrder = 2,
                            Text = "a bush pilot with a leather jacket and aviator goggles, beside a vintage propeller plane"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444412"),
                            Description = "Дослідник глибин серед яскравих коралових рифів",
                            Name = "Дайвер",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333303"),
                            SortOrder = 3,
                            Text = "a scuba diver with full diving gear, exploring a vivid coral reef underwater"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444413"),
                            Description = "Мандрівник з їздовими собаками серед арктичних льодів",
                            Name = "Полярник",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333303"),
                            SortOrder = 4,
                            Text = "a polar explorer in an expedition parka with sled dogs, amid arctic ice fields"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444419"),
                            Description = "Шукач пригод серед руїн у тропічних джунглях",
                            Name = "Дослідник джунглів",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333303"),
                            SortOrder = 5,
                            Text = "a jungle explorer with a khaki outfit and a machete, deep in lush tropical rainforest ruins"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444414"),
                            Description = "Маестро кухні за роботою над вишуканою стравою",
                            Name = "Шеф-кухар",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333304"),
                            SortOrder = 1,
                            Text = "a head chef in a pristine white uniform plating a dish, in a busy professional kitchen"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444415"),
                            Description = "Лікар у білому халаті в сучасній клініці",
                            Name = "Лікар",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333304"),
                            SortOrder = 2,
                            Text = "a doctor in a white coat with a stethoscope, in a bright modern hospital"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444416"),
                            Description = "Маестро у фраку перед великим оркестром",
                            Name = "Диригент",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333304"),
                            SortOrder = 3,
                            Text = "an orchestra conductor in a tailcoat mid-performance, baton raised before a grand orchestra"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444417"),
                            Description = "Рятувальник у спорядженні біля пожежної машини",
                            Name = "Пожежник",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333304"),
                            SortOrder = 4,
                            Text = "a firefighter in full turnout gear with a helmet, heroic pose near a fire engine"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444420"),
                            Description = "Космонавт у скафандрі під зоряним небом",
                            Name = "Астронавт",
                            PromptThemeId = new Guid("33333333-3333-3333-3333-333333333304"),
                            SortOrder = 5,
                            Text = "an astronaut in a detailed spacesuit with a reflective visor, beside a spacecraft under a starry sky"
                        });
                });

            modelBuilder.Entity("Calendary.Domain.Entities.PromptTheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PromptThemes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            Description = "вікінг, фараон, самурай, лицар, козак…",
                            Name = "Історія",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            Description = "нуар, вестерн, шпигун, мюзикл…",
                            Name = "Кіно",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            Description = "альпініст, пілот, дайвер, полярник…",
                            Name = "Пригоди",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333304"),
                            Description = "шеф, лікар, диригент, пожежник…",
                            Name = "Професії",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Sheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GeneratingStartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ImageStyleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PinnedPhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PromptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReadyAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActiveVariantId");

                    b.HasIndex("ImageStyleId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PinnedPhotoId");

                    b.HasIndex("PromptId");

                    b.ToTable("Sheets");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.SheetVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("CostUsd")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SheetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SheetId");

                    b.ToTable("SheetVariants");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EmailConfirmationAttempts")
                        .HasColumnType("int");

                    b.Property<string>("EmailConfirmationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailConfirmationCodeExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LastDeliveryCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastDeliveryPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastDeliveryRecipientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastDeliveryWarehouseAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastDeliveryWarehouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneVerificationAttempts")
                        .HasColumnType("int");

                    b.Property<string>("PhoneVerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PhoneVerificationCodeExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneVerificationPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneVerifiedPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Delivery", b =>
                {
                    b.HasOne("Calendary.Domain.Entities.Order", "Order")
                        .WithOne("Delivery")
                        .HasForeignKey("Calendary.Domain.Entities.Delivery", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Order", b =>
                {
                    b.HasOne("Calendary.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.OrderPhoto", b =>
                {
                    b.HasOne("Calendary.Domain.Entities.Order", "Order")
                        .WithMany("Photos")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Calendary.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Calendary.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.PersonalDate", b =>
                {
                    b.HasOne("Calendary.Domain.Entities.Order", "Order")
                        .WithMany("PersonalDates")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Prompt", b =>
                {
                    b.HasOne("Calendary.Domain.Entities.PromptTheme", "PromptTheme")
                        .WithMany("Prompts")
                        .HasForeignKey("PromptThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromptTheme");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Sheet", b =>
                {
                    b.HasOne("Calendary.Domain.Entities.SheetVariant", "ActiveVariant")
                        .WithMany()
                        .HasForeignKey("ActiveVariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Calendary.Domain.Entities.ImageStyle", "ImageStyle")
                        .WithMany()
                        .HasForeignKey("ImageStyleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Calendary.Domain.Entities.Order", "Order")
                        .WithMany("Sheets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Calendary.Domain.Entities.OrderPhoto", "PinnedPhoto")
                        .WithMany()
                        .HasForeignKey("PinnedPhotoId");

                    b.HasOne("Calendary.Domain.Entities.Prompt", "Prompt")
                        .WithMany()
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActiveVariant");

                    b.Navigation("ImageStyle");

                    b.Navigation("Order");

                    b.Navigation("PinnedPhoto");

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.SheetVariant", b =>
                {
                    b.HasOne("Calendary.Domain.Entities.Sheet", "Sheet")
                        .WithMany("Variants")
                        .HasForeignKey("SheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sheet");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("Calendary.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Order", b =>
                {
                    b.Navigation("Delivery");

                    b.Navigation("Payment");

                    b.Navigation("PersonalDates");

                    b.Navigation("Photos");

                    b.Navigation("Sheets");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.PromptTheme", b =>
                {
                    b.Navigation("Prompts");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.Sheet", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Calendary.Domain.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
